### ISSUE TITLE
Release notes on elemental.docs.rancher.com

### ISSUE THREAD

**Issue by kkaempf** [rancher/elemental-docs#165]
(This is a possible solution/workaround for https://github.com/rancher/elemental/issues/875)

As we release new versions (of elemental, elemental-operator, or the node image), we need a way to inform users
about the changes within.

Esp. the [backup/restore fix](https://github.com/rancher/elemental-operator/pull/477) needs manual intervention to take full effect.

We should start by enhancing our documentation with "release notes" for the various components.

Long-term, these release notes should be visible in the UI though.

**Comment by kkaempf** [comment]
Assigning to @nunix asking for respective docs infrastructure/setup so that engineering has a place to put release notes.

We need (at least) three components
- elemental (incl. elemental-toolkit, -register, and -cli)
- elemental-operator
- node image

Each component is versioned. Release notes are per-component, per-version.

**Comment by nunix** [comment]
Release notes page has been implemented. This issue can be closed.
