### ISSUE TITLE
Document elemental-operator and elemental-ui upgrade procedure

### ISSUE THREAD

**Issue by davidcassany** [rancher/elemental-docs#179]

**Comment by kkaempf** [comment]
@aalves08 - can you provide some input on how to upgrade elemental-ui please ?

**Comment by aalves08** [comment]
Hi @kkaempf .

What do you mean by `how to upgrade elemental-ui`?  Installing a newer version of the extension?

If so, you just go to the `Extensions` main menu entry in Rancher Dashboard -> go to the `Updates` tab -> click on the `Update` button on the card for the extension you want to upgrade -> Opens a new modal (by default it selects the latest version) and click `install`

![Screenshot 2023-08-08 at 16 43 04](https://github.com/rancher/elemental-docs/assets/97888974/9f8cb8c9-3dda-4acf-bc09-6bb772635da8)
![Screenshot 2023-08-08 at 16 43 13](https://github.com/rancher/elemental-docs/assets/97888974/9380e3ef-a703-4ff8-af5b-2965b2b8b1ae)

Is this it? Thanks 🙏

**Comment by kkaempf** [comment]
Closing as we have operater in the marketplace now
