### ISSUE TITLE
Remastering a Custom Docker Image overwrites /etc/os-release

### ISSUE THREAD

**Issue by tserong** [rancher/elemental-docs#180]
https://elemental.docs.rancher.com/customizing/#remastering-a-custom-docker-image includes the following snippet in the Dockerfile:

```
ARG IMAGE_REPO=norepo
ARG IMAGE_TAG=latest
RUN echo "IMAGE_REPO=${IMAGE_REPO}"          > /etc/os-release && \
    echo "IMAGE_TAG=${IMAGE_TAG}"           >> /etc/os-release && \
    echo "IMAGE=${IMAGE_REPO}:${IMAGE_TAG}" >> /etc/os-release
```

This entirely replaces the existing `/etc/os-release` file, so it only includes the `IMAGE_*` variables, and no longer has the OS name, version, id etc.

Given the elemental teal base image already includes those `IMAGE_*` variables, maybe something like this would be better?

```
RUN \
    sed -i -e "s/^IMAGE_REPO=.*/IMAGE_REPO=\"${IMAGE_REPO}\"/g"    /etc/os-release && \
    sed -i -e "s/^IMAGE_TAG=.*/IMAGE_TAG=\"${IMAGE_TAG}\"/g"       /etc/os-release && \
    sed -i -e "s/^IMAGE=.*/IMAGE=\"${IMAGE_REPO}:${IMAGE_TAG}\"/g" /etc/os-release
```

(Of course, that _won't_ work if those `IMAGE_*` variables aren't present in the base `/etc/os-release` file for some reason)

**Comment by kkaempf** [comment]
Thanks @tserong, good catch !
