### ISSUE TITLE
Installation: Prepare Installation Media refers to non-existent helper script

### ISSUE THREAD

**Issue by tserong** [rancher/elemental-docs#184]
https://elemental.docs.rancher.com/next/installation#prepare-installation-media says (emphasis mine):

The installation media is the media that will be used to kick start an Elemental Teal deployment. Currently the supported media is a live ISO. The live ISO must include the registration configuration yaml hence it must crafted once the MachineRegistration is created.  **The installation media is created by using the `elemental-iso-add-registration` helper script (see [quick start](https://elemental.docs.rancher.com/next/quickstart-cli#preparing-the-iso) guide)** or by using the elemental build-iso command line utility included as part of the [Elemental Toolkit](https://rancher.github.io/elemental-toolkit/docs/creating-derivatives/build_iso).

That helper script (`elemental-iso-add-registration`) doesn't exist in the docs anymore, so this section needs to be updated.

**Comment by fgiudici** [comment]
While there referencing the SeedImage, it may be worth  to introduce the cloud-init config option in the SeedImage, that could replace the following section:
[...]
 _In order to configure the installation beyond the common options provided within the [elemental.install](https://elemental.docs.rancher.com/next/machineregistration-reference#configelementalinstall) section a config.yaml configuration file can be included into the ISO_
 [...]
