### ISSUE TITLE
Document staging/dev (stable?) OBS

### ISSUE THREAD

**Issue by crisman** [rancher/elemental-docs#186]
In the quickstart docs the `helm upgrade` is wrapped in Tabs for staging and dev.  The warning under dev implies dev is more bleeding edge ("unstable"/"experimental").

Nothing seems to define what staging/dev mean.

Looking at OBS I see two more points of confusion:
- There is also a stable
- dev (v1.2.4) is currently behind staging/stable (v.1.2.5)

Please document:
- What is staging
- What is dev
- Why is stable ignored in the tab options
  - If stable should be in tabs, when to use stable instead of staging
- When to use dev (current warning only includes reasons not to use it)

OBS pages I was looking at for version inputs:
- https://build.opensuse.org/package/show/isv:Rancher:Elemental:Stable/elemental-operator-crds-helm
- https://build.opensuse.org/package/show/isv:Rancher:Elemental:Staging/elemental-operator-crds-helm
- https://build.opensuse.org/package/show/isv:Rancher:Elemental:Dev/elemental-operator-crds-helm

**Comment by fgiudici** [comment]
Thanks @crisman , this is a good point: we should be more verbose on the versions of the artifacts we deliver.

**Comment by kkaempf** [comment]
Here's the quick answer
* Stable: old, but tested
* Staging: build from latest git tags, ready to be tested
* Dev: build from 'tip of head' in git
