### ISSUE TITLE
Document upgrade from charts versions < 1.2.5

### ISSUE THREAD

**Issue by fgiudici** [rancher/elemental-docs#209]
So, in order to support upgrade from 1.1.0 (or anyway charts < 1.2.5) we added some logic to the elemental-operator-chart 1.2.5 (and only that one).
Only in that case would require the user to install the elemental-operator-chart first, and the crds one after.
Moreover, 1.2.5 intermediate steps is required to upgrade to newer ones.

We should document that clearly.

**Comment by kkaempf** [comment]
outdated
