### ISSUE TITLE
Update documentation with correct repositories

### ISSUE THREAD

**Issue by anmazzotti** [rancher/elemental-docs#210]
Looks like we have outdated references for a few things in the documentation:
- https://github.com/rancher/elemental-docs/blob/main/docs/quickstart-cli.md?plain=1#L178
- https://github.com/rancher/elemental-docs/blob/main/docs/quickstart-cli.md?plain=1#L188
- https://github.com/rancher/elemental-docs/blob/main/examples/quickstart/seedimage.yaml#L7

And some images:
- https://github.com/rancher/elemental-docs/blob/main/docs/images/upgrade-ui-version-channel.png
- https://github.com/rancher/elemental-docs/blob/main/docs/images/upgrade-ui-image-registry.png

Probably there is more.

**Comment by davidcassany** [comment]
Good catch, RPi images should be moved to staging and others to registry.suse.com

**Comment by kkaempf** [comment]
fixed by #216
