### ISSUE TITLE
Document the UI (evtl. replacing the current quickstart)

### ISSUE THREAD

**Issue by kkaempf** [rancher/elemental-docs#57]
The [current quickstart](http://elemental.docs.rancher.com/quickstart) is CLI focused since this was the only way to interact with Elemental in the beginning.

Meanwhile the [Elemental UI](https://github.com/rancher/elemental-ui) is matured, available as a Rancher extension (since Rancher 2.7.0) and will provide [ISO download](https://github.com/rancher/elemental-operator/issues/207) shortly.

It's about time to provide initial documentation for the UI, esp. targeting the current quickstart content and eventually replacing the cli-based quickstart with a UI-based one.

**Comment by agracey** [comment]
This might be a good time to pivot the flow of the documentation to be closer to how we expect the tooling to be used in production environments

**Comment by kkaempf** [comment]
#69 got merged
