### ISSUE TITLE
Document full story about how to use elemental behind proxy

### ISSUE THREAD

**Issue by juadk** [rancher/elemental-docs#71]
I would like a How-to Guides section in the documentation to tell how to configure elemental to be used behind a proxy.

In `sidebars.js` :
```
{
      "type": "category",
      "collapsible": true,
      "collapsed": false,
      "label": "How-to Guides",
      "items": [
        "elemental-behind-proxy"
      ]
    },
```

**Comment by kkaempf** [comment]
This needs to cover UI and CLI

**Comment by juadk** [comment]
> This needs to cover UI and CLI

hmm yes but you cannot configure cloud-init for seedimage in the UI.

**Comment by kkaempf** [comment]
https://github.com/rancher/elemental/pull/768#issuecomment-1491848996 is the answer I was looking for

**Comment by juadk** [comment]
ok ok, I thought you were talking about configuring the proxy in the seedimage (for elemental-register), all good then :-)
